# Use root/example as user/password credentials
version: '3.1'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: darknamer-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd

  mysql-adminer:
    image: adminer
    container_name: darknamer-mysql-adminer
    restart: always
    ports:
      - 8082:8082