version: '3.1'
services:
  owncloud:
    image: owncloud:10.0
    container_name: darknamer-owncloud
    restart: always
    ports:
     - 8443:80

  mysql:
    image: mariadb
    container_name: darknamer-mariadb
    restart: always
    ports: 
     - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd